# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c17c4ba10d5ac84ccc7998368110511003b8fd158eae778f4f38ae67178e39f1de39d4f005aed0141f275ab190ea1b5229d692b0f33f3302dbae5a27e45ede92

test:
  secret_key_base: 671657cc1b34f554ce35d7399b96ac09da1a4388053f24ce5018bf918baf785514ac9c60fe37356fe76889be4df30143eb76a755dda12242b33b49b88b067925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
